# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 390287323fba7659d6f64aee364acabcb8e2f7068a8f554a558af56b5f4ca223a77b1d0d2f8024059288fe40f8d5a5e2c47442df2e0c3e88b96f2272ebe3f3ff

test:
  secret_key_base: df55661f9c9c43824eac6b10d714de92e9d5730a53605a08ecde57832162b1b0c8f07183f78d86ba734bbe7c3ab1fe1af9b2996b1e191cfb47f0609b3c5a5a88

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
